baseurl = "https://blog.jordancrane.me/"
languageCode = "en-us"
title = "Jordan Crane's Blog"
theme = "bare"
pygmentsstyle = "emacs"
Paginate = 10

[params]
  mainSections = ["posts"]
  author = "Jordan Crane"
  email = "jordan@jordancrane.me"
  description = "Backend software engineer based in Portland, OR"
  postcss = true
  # Include the author name in the <title> of articles
  includeAuthorInTitle = true
  # Can be any colour here: https://bulma.io/documentation/layout/hero/#colors
  # e.g "warning" or "danger" for yellow or red.
  hero_colour = "link"
  disableAttribution = true
