baseurl = "https://blog.jordancrane.me/"
languageCode = "en-us"
title = "Blog-Standard"
theme = "bare"
pygmentsstyle = "emacs"
Paginate = 10

[params]
  mainSections = ["posts"]
  author = "Jordan Crane"
  email = "jordan@jordancrane.me"
  description = "Backend software engineer living in Portland, OR"
  postcss = false
  # Include the author name in the <title> of articles
  includeAuthorInTitle = true
  # Can be any colour here: https://bulma.io/documentation/layout/hero/#colors
  # e.g "warning" or "danger" for yellow or red.
  hero_colour = "link"
  disableAttribution = true

[[params.social]]
  icon = "github"
  url = "https://github.com/jordancrane/"

[[params.social]]
  icon = "linkedin"
  url = "https://linkedin.com/in/jordancrane"

[[params.social]]
  icon = "instagram"
  url = "https://www.instagram.com/jcrvne" 
